name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install dependencies
        run: npm ci
      - name: Install server dependencies
        run: npm --prefix server ci || (cd server && npm install)
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Run UI tests (start server and test)
        env:
          UI_HEADLESS: 'true'
          UI_BASE_URL: 'http://localhost:3000/'
        run: npm run test:ui:local
      - name: Run API tests
        run: npm run test:api
